---

- name: Generate peer certificate private key
  openssl_privatekey:
    path: "{{ data_ssl_dir }}/{{ data_ssl_peer_dir }}/{{ data_ssl_peer_key }}"
  tags:
    - certificates
    - client

- name: Generate peer certificate CSR
  openssl_csr:
    path: "{{ data_ssl_dir }}/{{ data_ssl_peer_dir }}/{{ data_ssl_peer_csr }}"
    privatekey_path: "{{ data_ssl_dir }}/{{ data_ssl_peer_dir }}/{{ data_ssl_peer_key }}"
    common_name: "{{ data_ssl_peer_cn|default( ansible_hostname ) }}"
    subject_alt_name:
      - "IP:{{ data_ssl_peer_ip }}"
      - "DNS:{{ data_ssl_peer_cn|default( ansible_hostname ) }}"
    basic_constraints:
      - CA:FALSE
    basic_constraints_critical: true
    extended_key_usage:
      - clientAuth
      - serverAuth
    force: false
  tags:
    - certificates
    - client

- name: Generate peer certificate
  openssl_certificate:
    path: "{{ data_ssl_dir }}/{{ data_ssl_peer_dir }}/{{ data_ssl_peer_cert }}"
    csr_path: "{{ data_ssl_dir }}/{{ data_ssl_peer_dir }}/{{ data_ssl_peer_csr }}"
    ownca_path: "{{ data_ssl_dir }}/{{ data_ssl_ca_dir }}/{{ data_ssl_ca_cert }}"
    ownca_privatekey_path: "{{ data_ssl_dir }}/{{ data_ssl_ca_dir }}/{{ data_ssl_ca_key }}"
    provider: ownca
    force: false
  tags:
    - certificates
    - client
